server {
    listen 80;

    # Serve o HTML/JS
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Encaminha chamadas de API para os containers Python
    location /api/clientes/ {
        proxy_pass http://cliente-service:5000/;
    }

    location /api/livros/ {
        proxy_pass http://livro-service:5000/;
    }

    location /api/emprestimos/ {
        proxy_pass http://emprestimo-service:5000/;
    }
}